### ISSUE TITLE
Using Spring boot Lettuce cannot connect Redis sentinel

### ISSUE THREAD

**Issue by new-biee** [redis/lettuce#2786]
I configured Redis Sentinel using docker-compose and used spring boot to connect to redis sentinel

### Docker-compose

```yml
redis-master:
    image: 'redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=admin
      - ALLOW_EMPTY_PASSWORD=yes
    command: "redis-server /etc/redis.conf"
    user: root
    volumes:
      - "./master.conf:/etc/redis.conf"
    ports:
      - "6379:6379"
    networks:
      mss-dev:
        aliases:
          - redis-master
        ipv4_address: 192.168.1.100

  redis-slave:
    image: 'redis:latest'
    command: "redis-server /etc/redis.conf --slaveof redis-master 6379 --masterauth admin"
    user: root
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=127.0.0.1
    volumes:
      - "./slave.conf:/etc/redis.conf"
    depends_on:
      - redis-master
    deploy:
      replicas: 2
    networks:
      mss-dev:
        aliases:
          - redis-slave
      
  redis-sentinel-1:
    image: 'redis:latest'
    command:   bash -c 
      "echo bind 127.0.0.1 > sentinel.conf &&
      echo 'port 26379' >> sentinel.conf &&
      echo 'dir /tmp' >> sentinel.conf &&
      echo 'protected-mode no' >> sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 5000' >> sentinel.conf &&
      echo 'sentinel auth-pass mymaster admin' >> sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
    volumes:
      - "./sentinel/sentinel.conf:/etc/redis.conf"
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - 26379:26379      
    networks:
      mss-dev:
        aliases:
          - redis-sentinel

  redis-sentinel-2:
    image: 'redis:latest'
    command:   bash -c 
      "echo bind 127.0.0.1 > sentinel.conf &&
      echo 'port 26379' >> sentinel.conf &&
      echo 'dir /tmp' >> sentinel.conf &&
      echo 'protected-mode no' >> sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 5000' >> sentinel.conf &&
      echo 'sentinel auth-pass mymaster admin' >> sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
    volumes:
      - "./sentinel/sentinel.conf:/etc/redis.conf"
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - 26380:26379
    networks:
      mss-dev:
        aliases:
          - redis-sentinel

  redis-sentinel-3:
    image: 'redis:latest'
    command:   bash -c 
      "echo bind 127.0.0.1 > sentinel.conf &&
      echo 'port 26379' >> sentinel.conf &&
      echo 'dir /tmp' >> sentinel.conf &&
      echo 'protected-mode no' >> sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 5000' >> sentinel.conf &&
      echo 'sentinel auth-pass mymaster admin' >> sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
    environment:
      - REDIS_MASTER_HOST=127.0.0.1
    volumes:
      - "./sentinel/sentinel.conf:/etc/redis.conf"
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - 26381:26379
    networks:
      mss-dev:
        aliases:
          - redis-sentinel
```

**slave.conf**

```conf
bind 127.0.0.1
protected-mode no
port 6379
replicaof redis-master 6379
masterauth admin
requirepass admin
```

**master.conf**

```conf
bind 127.0.0.1
protected-mode no
requirepass admin
appendonly yes
```

**application.yml**

```yml
spring
  cache:
    type: redis
    redis:
      time-to-live: 600
  redis:
    database: 0
    sentinel:
      master: mymaster
      password: admin
      nodes:
        - 127.0.0.1:26379
        - 127.0.0.1:26380
        - 127.0.0.1:26381
    lettuce:
      shutdown-timeout: 20000ms
```

**RedisConfig**

```java
@Bean
    public LettuceConnectionFactory connectionFactor() {
        LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
            .readFrom(ReadFrom.REPLICA_PREFERRED)
            .build();
        RedisSentinelConfiguration sentinelConfig = new RedisSentinelConfiguration()
            .master(redisProperties.getSentinel().getMaster());
        sentinelConfig.master("mymaster");
        sentinelConfig.sentinel("127.0.0.1", 26379);
        sentinelConfig.sentinel("127.0.0.1", 26380);
        sentinelConfig.sentinel("127.0.0.1", 26381);
        sentinelConfig.setPassword(RedisPassword.of(redisProperties.getPassword()));
        return new LettuceConnectionFactory(sentinelConfig, clientConfig);
    }
```

[log.txt](https://github.com/lettuce-io/lettuce-core/files/14589822/log.txt)

Please help me!
