### ISSUE TITLE
Support SSL for endpoint and no SSL for discovery service

### ISSUE THREAD

**Issue by tishun** [redis/lettuce#3141]
## Bug Report

When connecting to an SSL-enabled database we get an error.

#### Current Behavior

As per [best practises guide](https://redis.io/kb/doc/1vu47jcpnu/best-practices-to-use-the-sentinel-discovery-service) says

> The sentinel endpoint is UN-authenticated and will list all the databases and corresponding IP addresses. It has no TLS, which further adds complexity if TLS is enabled for a database at the framework client library level (e.g. Spring Data).

```yaml
spring:
 application:
  name: "myApp"
 data:
  redis:
   ssl:
    enable: true
   sentinel:
    username: theUsername
    password: thePassword
    master: theMaster
    nodes: IP_ADDRESS:8001, IP_ADDRESS:8001, IP_ADDRESS:8001
```

<details>
<summary>Stack trace</summary>

```java
2024-11-22 13:46:01,801 ERROR [lr002tom10009,service-digital-swift-manager,3010986,o.s.s.s.TaskUtils$LoggingErrorHandler ,     Job-1] ,, : Unexpected error occurred in scheduled task
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis
 
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to 10.179.251.6/<unresolved>:10100
Caused by: io.lettuce.core.RedisConnectionException: Connection closed prematurely```

</details>
